require('../lib/index')
const test = require('assert')

test.doesNotThrow(() => trace('ActionScript'))
test.doesNotThrow(() => System.out.println('Java'))
test.doesNotThrow(() => println('Kotlin'))
test.doesNotThrow(() => println('Processing'))
test.doesNotThrow(() => print('Python'))
test.doesNotThrow(() => fmt.printf('Go '))
test.doesNotThrow(() => fmt.println('Go'))
test.doesNotThrow(() => Console.Write('VB.NET '))
test.doesNotThrow(() => Console.WriteLine('VB.NET'))
