require('../lib/index')
const test = require('assert')

test.doesNotThrow(() => trace('ActionScript'))
test.doesNotThrow(() => fmt.printf('Go\n'))
test.doesNotThrow(() => fmt.println('Go'))
test.doesNotThrow(() => System.out.println('Java'))
test.doesNotThrow(() => println('Kotlin'))
test.doesNotThrow(() => io.write('Lua\n'))
test.doesNotThrow(() => println('Processing'))
test.doesNotThrow(() => print('Python'))
test.doesNotThrow(() => Console.Write('C#/VB.NET\n'))
test.doesNotThrow(() => Console.WriteLine('C#/VB.NET'))
