require('../lib/polyglot')
const tap = require('tap')

tap.test('Print functions', function (t) {
  printf('C\n')
  IO.write('Elixir\n')
  fmt.Printf('Go\n')
  putStr('Haskell\n')
  io.write('Lua\n')
  fprintf('Matlab\n')
  Write('Pascal\n')
  write('Pike\n')
  t.end()
})

tap.test('Print with new line', function (t) {
  trace('ActionScript')
  WriteF('AmigaE')
  Response.Write('ASP')
  putschar('B')
  puts('C')
  Console.println('C#')
  Console.WriteLine('C#')
  writeln('D')
  std.stdio.writeln('D')
  print('Dart')
  Writeln('Delphi')
  IO.puts('Elixir')
  fmt.Println('Go')
  putStrLn('Haskell')
  System.out.println('Java')
  console.log('JavaScript')
  println('Kotlin')
  disp('Matlab')
  echo('Nim')
  NSLog('Objetive-C')
  writeln('Pascal')
  writeln('Pike')
  println('Processing')
  PrintN('PureBasic')
  print('Python')
  p('Ruby')
  t.end()
})